Raid controller and Physical Drive attributes need to be nullable
This can fail with
AttributeError: 'NoneType' object has no attribute 'strip'
otherwise

Closes-Bug: #1550328
Change-Id: I8eafe606407cddc1e9ea03a33473b65ff3b59384